### ISSUE TITLE
Mobile responsiveness issue.

### ISSUE THREAD

**Issue by DevSrijit** [mirayatech/NinjaSketch#1]
Hey,
I just wanted to point out that the help button on the to right section of the page, gets overlayed by the tool bar on mobile screens.

**Comment by mirayatech** [comment]
Just as it says in the README, the app is not responsive. I mainly focused on the functionalities, since I already have plenty of projects that are responsive.

**Comment by mirayatech** [comment]
Just as it says in the README, the app is not responsive. I mainly focused on the functionalities, since I already have plenty of projects that are responsive.
